---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2-web
  template:
    metadata:
      labels:
        app: project2-web
    
    spec:
      containers:
      - name: project2-web
        image: quay.io/ran_ju_vincie/cs401_project2_0:a4274b0
        ports:
        - containerPort: 5005
